name: FastAPI CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn

    - name: Run tests
      run: |
        echo "No tests to run"

    - name: Start server
      run: |
        uvicorn main:app --host 0.0.0.0 --port 8000
      background: true

    - name: Wait for server to start
      run: |
        sleep 10

    - name: Test server
      run: |
        curl -s -o /dev/null -w "%{http_code}" http://localhost:8000 | grep "200"